global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'collector-backend'
    scheme: https
    # IMPORTANT : targets doit etre "host:port", pas "https://...". Le scheme est defini au dessus.
    metrics_path: /api/metrics
    # Essayons l'adresse interne pour eviter le hairpinning du Load Balancer
    static_configs:
      - targets: ['collector-backend.internal.wittyforest-1d08efa7.francecentral.azurecontainerapps.io:443']
    tls_config:
      insecure_skip_verify: true

  # On surveille le Frontend (Nginx), il n'expose pas de /metrics mais on veut savoir s'il repond (UP)
  # - job_name: 'collector-frontend'
  #   scheme: https
  #   metrics_path: /
  #   static_configs:
  #     - targets: ['collector-frontend.internal.wittyforest-1d08efa7.francecentral.azurecontainerapps.io:443']
  #   tls_config:
  #     insecure_skip_verify: true

  # On surveille Keycloak (Auth), avec les metrics activees
  - job_name: 'collector-auth'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ['collector-auth.internal.wittyforest-1d08efa7.francecentral.azurecontainerapps.io:443']
    tls_config:
      insecure_skip_verify: true
